// Team5_Debateverse/lalit/frontend/src/components/Register.jsx
import React, { useState } from 'react';
import axios from 'axios';
import { Link, useNavigate } from 'react-router-dom';

const Register = () => {
  const navigate = useNavigate();
  const [data, setData] = useState({
    username: '',
    email: '',
    password: '',
    confirmpassword: '',
  });

  const [errorMessage, setErrorMessage] = useState('');
  const [successMessage, setSuccessMessage] = useState('');
  const [loading, setLoading] = useState(false);

  const changeHandler = (e) => {
    setData({ ...data, [e.target.name]: e.target.value });
    setErrorMessage('');
    setSuccessMessage('');
  };

  const submitHandler = async (e) => {
    e.preventDefault();

    if (!data.username || !data.email || !data.password || !data.confirmpassword) {
      setErrorMessage('All fields are required.');
      setSuccessMessage('');
      return;
    }

    const emailRegex = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$/;
    if (!emailRegex.test(data.email)) {
      setErrorMessage('Please enter a valid email address.');
      setSuccessMessage('');
      return;
    }

    if (data.password !== data.confirmpassword) {
      setErrorMessage('Passwords do not match.');
      setSuccessMessage('');
      return;
    }

    setLoading(true); 
    try {
      console.log(data)
      const res = await axios.post('http://localhost:5000/register', data);

      setSuccessMessage('Registration successful! Please check your email for confirmation.');
      setErrorMessage('');
      setLoading(false); 

      navigate('/registersuccess');
    } catch (error) {
      if (error.response?.data?.error === 'User Already Exist') {
        console.log(error.response?.data?.error);
        setErrorMessage('Email already exists. Please log in.');
      } else if (error.response?.data?.error === 'Passwords do not match') {
        setErrorMessage('Passwords do not match.');
      } else {
        setErrorMessage('Registration failed. Please try again.');
      }
      setLoading(false); 
      setSuccessMessage('');
    }
  };

  return (
    <div className="h-[calc(100vh-120px)] flex justify-center items-center">
      <div className="w-full max-w-sm mx-auto bg-white/80 shadow-md rounded px-8 pt-6 pb-8 mb-4">
        <h2 className="text-xl font-semibold mb-4">Please Register</h2>
        <form onSubmit={submitHandler}>
        <div className="mb-2">
            <label className="block text-gray-700 text-sm mb-1" htmlFor="username">
              Your Name
            </label>
            <input
              type="text"
              onChange={changeHandler}
              name="username"
              id="username"
              placeholder="Name"
              value={data.username}
              className="shadow appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow"
            />
          </div>
          <div className="mb-2">
            <label className="block text-gray-700 text-sm mb-1" htmlFor="email">
              Email
            </label>
            <input
              type="email"
              onChange={changeHandler}
              name="email"
              id="email"
              placeholder="Email Address"
              value={data.email}
              className="shadow appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow"
            />
          </div>
          <div className="mb-2">
            <label className="block text-gray-700 text-sm mb-1" htmlFor="password">
              Password
            </label>
            <input
              type="password"
              onChange={changeHandler}
              name="password"
              id="password"
              placeholder="Password"
              value={data.password}
              className="shadow appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow"
            />
          </div>
          <div className="mb-2">
            <label
              className="block text-gray-700 text-sm mb-1"
              htmlFor="confirmpassword"
            >
              Confirm Password
            </label>
            <input
              type="password"
              onChange={changeHandler}
              name="confirmpassword"
              id="confirmpassword"
              placeholder="Confirm Password"
              value={data.confirmpassword}
              className="shadow appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow"
            />
          </div>
          {errorMessage && (
            <p className="text-red-500 text-xs italic mb-4">{errorMessage}</p>
          )}
          {successMessage && (
            <p className="text-green-500 text-xs italic mb-4">{successMessage}</p>
          )}
          {loading && (
            <p className="text-blue-700 text-xs font-bold italic mb-4">Please wait...</p>
          )}
          <div>
            <button
              type="submit"
              className="bg-gray-700 hover:bg-gray-500 text-white font-bold py-2 px-8 rounded focus:outline-none"
              disabled={loading} 
            >
              Submit
            </button>
          </div>
        </form>
        <p className="align-baseline font-medium mt-4 mb-2 text-sm">
          Already have an account? Please{' '}
          <Link to="/login" className="text-blue-500 hover:text-blue-700">
            Login
          </Link>
        </p>
      </div>
    </div>
  );
};

export default Register;

// Team1_Debateverse/mohitsingh/frontend-angular/src/app/auth/register/register.component.ts
import { Component } from '@angular/core';
import { MatSnackBar } from '@angular/material/snack-bar';
import { Router } from '@angular/router';
import { AuthServiceService } from '../../services/auth-service/auth-service.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrl: './register.component.css',
})
export class RegisterComponent {
  user: any = {
    email: '',
    password: '',
  };

  confirmPass: any = '';

  constructor(
    private _auth: AuthServiceService,
    private _snack: MatSnackBar,
    private _router: Router
  ) {}

  register() {
    if (this.user.password !== this.confirmPass) {
      this._snack.open('Passwords do not match', 'Close', {
        duration: 2000,
        verticalPosition: 'bottom',
        horizontalPosition: 'right',
      });
      return;
    }

    console.log(this.user);

    this._auth.register(this.user).subscribe({
      next: (res: any) => {
        if (res.success) {
          console.log(res.message);
          this._snack.open(res.message || 'User registered successfully', 'Close', {
            duration: 2000,
            verticalPosition: 'bottom',
            horizontalPosition: 'right',
          });
          this._router.navigate(['/verify-email'], {
            queryParams: { email: this.user.email },
          });
        } else {
          this._snack.open(res.message || 'Registration failed', 'Close', {
            duration: 2000,
            verticalPosition: 'bottom',
            horizontalPosition: 'right',
          });
        }
      },
      error: (err) => {
        console.log(err);
        this._snack.open(err.error.message || 'Something went wrong!', 'Close', {
          duration: 2000,
          verticalPosition: 'bottom',
          horizontalPosition: 'right',
        });
      },
    });
  }

}

<section class="bg-gray-100 dark:bg-gray-900">
  <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
    <!-- <a href="#" class="flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white">
          <img class="w-8 h-8 mr-2" src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/logo.svg" alt="logo">
          Flowbite
      </a> -->
    <div *ngIf="errors.length>0"
      class="flex items-center p-4 mb-4 text-sm text-red-800 border border-red-300 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400 dark:border-red-800"
      role="alert">
      <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
        fill="currentColor" viewBox="0 0 20 20">
        <path
          d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z" />
      </svg>
      <span class="sr-only">Info</span>
      <div>
        <span class="font-medium"></span> {{errors}}
      </div>
    </div>
    <div
      class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
      <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
        <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
          Create an account
        </h1>
        <form class="space-y-4 md:space-y-6" action="#">
          <!-- username -->
          <div>
            <label for="name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your username</label>
            <input type="text" name="name" id="name"
              class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="John Doe" required="" [(ngModel)]="user.name">
          </div>


          <div>
            <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your email</label>
            <input type="email" name="email" id="email"
              class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="name@company.com" required="" [(ngModel)]="user.email">
          </div>
          <div>
            <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Password</label>
            <input type="password" name="password" id="password" placeholder="••••••••"
              class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              required="" [(ngModel)]="user.password">
          </div>
          <div>
            <label for="confirm-password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Confirm
              password</label>
            <input type="password" name="confirm-password" id="confirm-password" placeholder="••••••••"
              class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              required="" [(ngModel)]="user.confPass">
          </div>
          <!-- <div class="flex items-start">
                      <div class="flex items-center h-5">
                        <input id="terms" aria-describedby="terms" type="checkbox" class="w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-primary-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-primary-600 dark:ring-offset-gray-800" required="">
                      </div>
                      <div class="ml-3 text-sm">
                        <label for="terms" class="font-light text-gray-500 dark:text-gray-300">I accept the <a class="font-medium text-primary-600 hover:underline dark:text-primary-500" href="#">Terms and Conditions</a></label>
                      </div>
                  </div> -->
          <button type="submit" (click)="register()"
            class="w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Create
            an account</button>
          <p class="text-sm font-light text-gray-500 dark:text-gray-400">
            Already have an account? <a href="#" routerLink="/login"
              class="font-medium text-primary-600 hover:underline dark:text-primary-500">Login here</a>
          </p>
        </form>
      </div>
    </div>
  </div>
</section>
