// Team1_Debateverse/mohitsingh/frontend-angular/src/app/auth/login/login.component.ts
import { Component } from '@angular/core';
import { AuthServiceService } from '../../services/auth-service/auth-service.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrl: './login.component.css',
})
export class LoginComponent {
  constructor(private _auth: AuthServiceService) {}

  user: any = {
    email: '',
    password: '',
  };

  login() {
    console.log(this.user);
    this._auth.login(this.user);
  }
}

<section class="bg-gray-100 dark:bg-gray-900">
  <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
      <!-- <a href="#" class="flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white">
          <img class="w-8 h-8 mr-2" src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/logo.svg" alt="logo">
          Flowbite
      </a> -->
      <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
          <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
              <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                  Sign in to your account
              </h1>
              <form class="space-y-4 md:space-y-6" action="#">
                  <div>
                      <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your email</label>
                      <input type="email" name="email" id="email" class="bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="name@company.com" required="" [(ngModel)]="user.email">
                  </div>
                  <div>
                      <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Password</label>
                      <input type="password" name="password" id="password" placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required="" [(ngModel)]="user.password">
                  </div>
                  <div class="flex items-center justify-between">
                      <div class="flex items-start">
                          <div class="flex items-center h-5">
                            <input id="remember" aria-describedby="remember" type="checkbox" class="w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-primary-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-primary-600 dark:ring-offset-gray-800" required="">
                          </div>
                          <div class="ml-3 text-sm">
                            <label for="remember" class="text-gray-500 dark:text-gray-300">Remember me</label>
                          </div>
                      </div>
                      <a href="#" routerLink="/forgot-password" class="text-sm font-medium text-primary-600 hover:underline dark:text-primary-500">Forgot password?</a>
                  </div>
                  <button type="submit" (click)="login()" class="w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Sign in</button>
                  <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                      Don’t have an account yet? <a href="#" routerLink="/register" class="font-medium text-primary-600 hover:underline dark:text-primary-500">Sign up</a>
                  </p>
              </form>
          </div>
      </div>
  </div>
</section>

// Team5_Debateverse/leelalakshmi/client/src/components/Login.jsx
import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { FcGoogle } from "react-icons/fc";
import { useForm } from "react-hook-form";
import { useAuth } from '../context/AuthContext';

const Login = () => {
    const [message, setMessage] = useState("");
    const {loginUser,signInWithGoogle} = useAuth();
    const navigate = useNavigate();

    const { register, handleSubmit, formState: { errors } } = useForm();

    const onSubmit = async (data) => {
        // Mock validation check
        try {
            await loginUser(data.email,data.password);
            alert("Login successfull");
            navigate("/")
        } catch (error) {
            setMessage("Please provide a valid email and password")
            console.log(error) 
        }
        
    };

    const handleGoogleSignIn = async () => {
        // Google sign-in logic
        try {
            await signInWithGoogle();
            alert("Login successful!")
            navigate("/")
        } catch (error) {
            alert("Google sign in failed")
            console.log(error) 
        }
    };

    return (
        <div className="h-[calc(100vh-120px)] flex justify-center items-center">
            <div className="w-full max-w-sm mx-auto bg-white/80 shadow-md rounded px-8 pt-6 pb-8 mb-4">
                <h2 className="text-xl font-semibold mb-4">Please Login</h2>

                <form onSubmit={handleSubmit(onSubmit)}>
                    <div className='mb-4'>
                        <label className='block text-gray-700 text-sm mb-2' htmlFor='email'>Email</label>
                        <input 
                            {...register("email", { required: true })}
                            type='email' 
                            name='email' 
                            id='email' 
                            placeholder='Email Address' 
                            className='shadow appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow' 
                        />
                        {errors.email && <p className="text-red-500 text-xs italic">Email is required</p>}
                    </div>

                    <div className='mb-4'>
                        <label className='block text-gray-700 text-sm mb-2' htmlFor='password'>Password</label>
                        <input 
                            {...register("password", { required: true })}
                            type='password' 
                            name='password' 
                            id='password' 
                            placeholder='Password' 
                            className='shadow appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow' 
                        />
                        {errors.password && <p className="text-red-500 text-xs italic">Password is required</p>}
                    </div>

                    {message && <p className='text-red-500 text-xs italic mb-3'>{message}</p>}

                    <div>
                        <button className='bg-gray-700 hover:bg-gray-500 text-white font-bold py-2 px-8 rounded focus:outline-none'>Submit</button>
                    </div>
                </form>

                <p className='align-baseline font-medium mt-4 mb-2 text-sm'>
                    Haven't an account? Please <Link to='/register' className='text-blue-500 hover:text-blue-700'>Register</Link>
                </p>

                {/* Google sign-in */}
                <div>
                    <button 
                        onClick={handleGoogleSignIn}
                        className='w-full flex items-center justify-center bg-blue-800 hover:bg-blue-700 text-white py-2 px-4 rounded focus:outline-none'
                    >
                        <FcGoogle className='mr-2' />
                        Sign in with Google
                    </button>
                </div>
            </div>
        </div>
    );
};

export default Login;
