// Team5_Debateverse/keerthi/frontend/src/Register.jsx
import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import axios from 'axios';

function Register() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [error, setError] = useState(null);
  const navigate = useNavigate();

  const validateEmail = (email) => {
    const regex = /^[\w-]+(\.[\w-]+)*@([\w-]+\.)+[a-zA-Z]{2,7}$/;
    return regex.test(email);
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    if (!validateEmail(email)) {
      setError("Invalid Email");
      return;
    }

    if (password !== confirmPassword) {
      setError("Passwords do not match");
      return;
    }

    setError(null);

    axios.post('http://localhost:3001/register', { email, password })
      .then(result => {
        if (result.data === "EMAIL_ALREADY_EXISTS") {
          setError("This email is already registered. Please use a different one.");
        } else if (result.data === "Success") {
          navigate('/home');
        }
      })
      .catch(err => {
        console.error(err);
        setError("Unable to process registration at this time. Please try again later.");
      });
  };

  return (
    <div className="d-flex justify-content-center align-items-center vh-100">
      <div className="bg-white p-4 rounded w-25 shadow">
        <h2 className="text-center mb-4">Register</h2>
        <form onSubmit={handleSubmit}>
          <div className="mb-3">
            <input
              type="email"
              placeholder="Enter email"
              name="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              autoComplete="off"
              className="form-control rounded-0"
            />
          </div>
          <div className="mb-3">
            <input
              type="password"
              placeholder="Enter password"
              name="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="form-control rounded-0"
            />
          </div>
          <div className="mb-3">
            <input
              type="password"
              placeholder="Confirm Password"
              name="confirmPassword"
              value={confirmPassword}
              onChange={(e) => setConfirmPassword(e.target.value)}
              className="form-control rounded-0"
            />
          </div>
          {error && <div className="text-danger mb-3">{error}</div>}
          <button type="submit" className="btn btn-success w-100">
            Register
          </button>
        </form>
        <div className="mt-3 text-center">
          <p>
            Already have an account? <Link to="/login">Login</Link>
          </p>
        </div>
      </div>
    </div>
  );
}

export default Register;

// src/app/register/register.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Router } from '@angular/router';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent {
  email = '';
  password = '';
  confirmPassword = '';
  role = 'USER';
  errorMessage = '';

  constructor(private http: HttpClient, private router: Router) {}

  register() {
    if (this.password !== this.confirmPassword) {
      this.errorMessage = 'Passwords do not match!';
      return;
    }
    const userData = { email: this.email, password: this.password, role: this.role };
    this.http.post('http://localhost:8090/api/auth/register', userData)
      .subscribe({
        next: () => {
        alert('Registration successful! Please login.');
        this.router.navigate(['/login']);
      }, 
      error: (error) => {
        console.error('Registration error:', error);
        this.errorMessage = error.error;
      }
      });
  }
}

<div class="form-container">
  <h2>Register</h2>
  <div class="form-box">
    <form (ngSubmit)="register()">
      <input [(ngModel)]="email" name="email" placeholder="Enter your email" type="email" required />
      <input [(ngModel)]="password" name="password" placeholder="Enter your password" type="password" required />
      <input [(ngModel)]="confirmPassword" name="confirmPassword" placeholder="Confirm your password" type="password" required />
      <button type="submit">Register</button>
      <div *ngIf="errorMessage" class="error">{{ errorMessage }}</div>
      <p class="switch-link">
        Already have an account? <a routerLink="/login">Login here</a>
      </p>
    </form>
  </div>
</div>
