// Team1_Debateverse/mohitsingh/frontend-angular/src/app/pages/home-routes/debates/debates.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-debates',
  templateUrl: './debates.component.html',
  styleUrl: './debates.component.css'
})
export class DebatesComponent {

}

<div class="bg-gray-100">
  <div class="min-h-screen mx-auto max-w-7xl p-4">
    <div class="grid gap-6 md:grid-cols-[300px_1fr]">
      <!-- Left Sidebar -->
      <div class="space-y-6">
        <!-- Back Button -->
        <button routerLink="/user"
          class="w-full justify-start bg-orange-500 hover:bg-orange-600 text-white font-bold p-3 rounded shadow-md">
          Back to Dashboard
        </button>

        <!-- Search Bar -->
        <div class="bg-orange-100 p-4 rounded shadow-md">
          <div class="relative">
            <input type="text" class="w-full pl-3 pr-10 py-2 rounded bg-white border focus:ring-2 focus:ring-orange-400"
              placeholder="Search..." [(ngModel)]="searchQuery" (keyup)="onSearch()" />
            <button (click)="onSearch()" class="absolute right-3 top-2.5 text-gray-500 hover:text-gray-700">
              🔍
            </button>
          </div>
        </div>

        <!-- Filters -->
        <div class="bg-white p-4 space-y-6 rounded shadow-md">
          <div class="space-y-4">
            <div>
              <label class="block text-sm font-medium mb-1">Likes greater than</label>
              <input type="range" min="0" max="50" [(ngModel)]="likes" (input)="onFilterChange()"
                class="w-full appearance-none bg-gray-200 h-2 rounded-lg cursor-pointer accent-blue-500" />
              <span class="block text-sm font-medium mt-2">Selected: {{ likes }}</span>
            </div>
            <div>
              <label class="block text-sm font-medium mb-1">Votes greater than</label>
              <input type="range" min="0" max="50" [(ngModel)]="votes" (input)="onFilterChange()"
                class="w-full appearance-none bg-gray-200 h-2 rounded-lg cursor-pointer accent-blue-500" />
              <span class="block text-sm font-medium mt-2">Selected: {{ votes }}</span>
            </div>
          </div>
          <div>
            <label class="block text-sm font-medium mb-1">Posted After</label>
            <input type="date" class="w-full p-2 rounded border focus:ring-2 focus:ring-orange-400"
              [(ngModel)]="postedAfter" (change)="onFilterChange()" />
          </div>
        </div>
      </div>

      <!-- Main Content -->
      <div class="space-y-6">


        <!-- Debate Cards -->
        <div *ngIf="filteredDebates.length > 0; else noDebates" class="space-y-6">
          <div *ngFor="let post of filteredDebates" class="bg-white p-6 rounded shadow-md">
            <div class="grid grid-cols-12 gap-4">
              <!-- Left Section -->
              <div class="col-span-9 space-y-2">
                <a href="#" [routerLink]="['/debate/', post.id]">
                  <p class="text-lg font-semibold text-indigo-600 hover:underline">{{ post.text }}</p>
                </a>
                <div class="text-sm text-gray-500">
                  <p>Posted by <span class="text-indigo-500 underline">{{ post.createdBy.name }}</span></p>
                  <p>on {{ post.createdOn | date }}</p>
                </div>
              </div>

              <!-- Right Section -->
              <div class="col-span-3 flex flex-col items-end space-y-2">
                <div class="flex items-center gap-1 text-red-500">
                  ❤️ <span>{{ post.totalLikes }}</span>
                </div>
                <div *ngIf="post.blocked == true"
                  class="mt-2 px-2 py-1 bg-gray-300 text-gray-600 text-xs font-semibold rounded">
                  Closed Debate
                </div>
                <div class="w-full mt-2">
                  <canvasjs-chart [options]="post.chartOptions" [styles]="{ width: '100%', height: '120px' }">
                  </canvasjs-chart>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- No Content Fallback -->
        <ng-template #noDebates>
          <div class="bg-white p-6 rounded shadow-md text-center">
            <p class="text-indigo-600 text-lg font-medium">No debates found</p>
          </div>
        </ng-template>

        <mat-paginator [length]="totalElements" [pageSize]="size" [pageSizeOptions]="[5, 10, 25]" aria-label="Select page" (page)="onPageChange($event)">
        </mat-paginator>

      </div>
    </div>
  </div>
</div>

// Team4_Debateverse/Dhev/frontend/src/pages/Debates.jsx

import { useNavigate, Link } from 'react-router-dom';
import { Search, Calendar } from 'lucide-react';
import VoteGraph from '../components/VoteGraph';
import { useEffect, useState } from "react";
const Debates = () => {
  const navigate = useNavigate();
  const [debates, setDebates] = useState([]);

  useEffect(() => {
    const fetchDebates = async () => {
      try {
        const response = await fetch("http://localhost:5000/api/debates");
        const data = await response.json();
        setDebates(data);
      } catch (error) {
        console.error("Error fetching debates: ", error);
      }
    };
    fetchDebates();
  }, []);


  
  const [searchTerm, setSearchTerm] = useState('');
  const [exactMatch, setExactMatch] = useState(false);
  const [minLikes, setMinLikes] = useState(0);
  const [minVotes, setMinVotes] = useState(0);
  const [dateAfter, setDateAfter] = useState('');

  const filteredDebates = debates.filter(debate => {
    const matchesSearch = exactMatch 
      ? debate.title.toLowerCase() === searchTerm.toLowerCase()
      : debate.title.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesLikes = debate.likes >= minLikes;
    const matchesVotes = debate.options.some(opt => opt.votes >= minVotes);
    const matchesDate = !dateAfter || new Date(debate.createdAt) >= new Date(dateAfter);
    return matchesSearch && matchesLikes && matchesVotes && matchesDate;
  });

  return (
    <div className="min-h-screen bg-gray-690 bg-opacity-75 backdrop-filter backdrop-blur-xl rounded-2xl shadow-xl overflow-hiddenp-6">
      <div className="max-w-6xl mx-auto">
        <div className="flex justify-between items-center mb-8">
          <button 
            onClick={() => navigate('/')}
            className="px-6 py-2 bg-gradient-to-r from-green-500 to-emerald-600 text-white font-bold rounded-lg shadow-lg"
          >
            Back to Dashboard
          </button>
          <div className="relative flex-1 max-w-xl mx-8">
            <Search className="absolute left-3 top-2.5 text-gray-400" size={20} />
            <input
              type="text"
              placeholder="Search debates..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full pl-10 pr-4 py-2 border-2 border-orange-300 rounded-lg font-comic"
            />
          </div>
        </div>

        <div className="grid grid-cols-4 gap-8">
          <div className="col-span-1 bg-white rounded-lg shadow-lg p-6 h-[50vh]">
            <div className="space-y-6 font-comic">
              <div>
                <label className="flex items-center space-x-2">
                  <input
                    type="checkbox"
                    checked={exactMatch}
                    onChange={(e) => setExactMatch(e.target.checked)}
                    className="w-4 h-4 rounded border-gray-300"
                  />
                  <span>Exact Match</span>
                </label>
              </div>

              <div>
                <label className="block mb-2">Likes greater than</label>
                <input
                  type="range"
                  min="0"
                  max="10000"
                  value={minLikes}
                  onChange={(e) => setMinLikes(Number(e.target.value))}
                  className="w-full h-2 bg-orange-200 rounded-lg appearance-none"
                />
                <div className="flex justify-between text-xs mt-1">
                  <span>0</span>
                  <span>{minLikes}</span>
                  <span>10k+</span>
                </div>
              </div>

              <div>
                <label className="block mb-2">Votes greater than</label>
                <input
                  type="range"
                  min="0"
                  max="25000"
                  value={minVotes}
                  onChange={(e) => setMinVotes(Number(e.target.value))}
                  className="w-full h-2 bg-orange-200 rounded-lg appearance-none"
                />
                <div className="flex justify-between text-xs mt-1">
                  <span>0</span>
                  <span>{minVotes}</span>
                  <span>25k+</span>
                </div>
              </div>

              <div>
                <label className="block mb-2">Posted After</label>
                <div className="relative">
                  <Calendar className="absolute left-3 top-2.5 text-gray-400" size={20} />
                  <input
                    type="date"
                    value={dateAfter}
                    onChange={(e) => setDateAfter(e.target.value)}
                    className="w-full pl-10 pr-4 py-2 border rounded-lg"
                  />
                </div>
              </div>
            </div>
          </div>

          <div className="col-span-3 space-y-4">
            {filteredDebates.map((debate) => (
              <div 
                key={debate.id}
                onClick={() => navigate(`/debates/${debate.id}`)}
                className="bg-white rounded-lg shadow-lg p-6 cursor-pointer hover:shadow-xl"
              >
                <div className="flex justify-between items-start mb-4">
                  <div>
                    <h3 className="text-lg font-semibold bg-gradient-to-r from-green-400 to-emerald-500 text-transparent bg-clip-text font-comic">
                      {debate.title}
                    </h3>
                    <p className="text-sm text-gray-600 mt-1 font-comic">
                      Posted by{' '}
                      <Link
                        to={`/user/${debate.createdBy}`}
                        className="text-blue-500 hover:underline"
                        onClick={(e) => e.stopPropagation()}
                      >
                        {debate.createdBy}
                      </Link>
                      {' '}on {new Date(debate.createdAt).toLocaleDateString()}
                    </p>
                  </div>
                  <div className="flex items-center gap-1 text-red-500 font-comic">
                    <span>❤️ {debate.likes}</span>
                  </div>
                </div>

                <VoteGraph options={debate.options} compact={true} />
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Debates;
